-- XXX stolen from tpope's config
vim.cmd.cabbrev("grpe grep")

if vim.fn.exists(":Abolish") > 0 then
  vim.cmd([[Abolish afterword{,s}                         afterward{}]])
  vim.cmd([[Abolish anomol{y,ies}                         anomal{}]])
  vim.cmd([[Abolish cal{a,e}nder{,s}                      cal{e}ndar{}]])
  vim.cmd([[Abolish {c,m}arraige{,s}                      {}arriage{}]])
  vim.cmd([[Abolish {,in}consistan{cy,cies,t,tly}         {}consisten{}]])
  vim.cmd([[Abolish destionation{,s}                      destination{}]])
  vim.cmd([[Abolish delimeter{,s}                         delimiter{}]])
  vim.cmd([[Abolish {,non}existan{ce,t}                   {}existen{}]])
  vim.cmd([[Abolish despara{te,tely,tion}                 despera{}]])
  vim.cmd([[Abolish hense                                 hence]])
  vim.cmd([[Abolish {,re}impliment{,s,ing,ed,ation}       {}implement{}]])
  vim.cmd([[Abolish improvment{,s}                        improvement{}]])
  vim.cmd([[Abolish inherant{,ly}                         inherent{}]])
  vim.cmd([[Abolish lastest                               latest]])
  vim.cmd([[Abolish {les,compar,compari}sion{,s}          {les,compari,compari}son{}]])
  vim.cmd([[Abolish {,un}nec{ce,ces,e}sar{y,ily}          {}nec{es}sar{}]])
  vim.cmd([[Abolish {,un}orgin{,al}                       {}origin{}]])
  vim.cmd([[Abolish persistan{ce,t,tly}                   persisten{}]])
  vim.cmd([[Abolish referesh{,es}                         refresh{}]])
  vim.cmd([[Abolish {,ir}releven{ce,cy,t,tly}             {}relevan{}]])
  vim.cmd([[Abolish rec{co,com,o}mend{,s,ed,ing,ation}    rec{om}mend{}]])
  vim.cmd([[Abolish reproducable                          reproducible]])
  vim.cmd([[Abolish resouce{,s}                           resource{}]])
  vim.cmd([[Abolish restraunt{,s}                         restaurant{}]])
  vim.cmd([[Abolish seperat{e,es,ed,ing,ely,ion,ions,or}  separat{}]])
  vim.cmd([[Abolish segument{,s,ed,ation}                 segment{}]])
  vim.cmd([[Abolish re{c,v}ieve                           receive]])
end
