#!/usr/bin/env fish

source env

function install
    echo "test/install()!"
end

function link
    _mklink test testrc
    _mklink test testrc "$HOME/.testrc"
end

function unlink
    _cleanup test
    _cleanup test "$HOME/.testrc"
end

function delete
    echo "test/delete()!"
end
