#!/usr/bin/env fish
source env

function install
    brew install \
    git git-lfs hub diff-so-fancy git-standup \
    git-extras git-flow-avh
end

function link
    _mklink git ignore
    _mklink git config
    _mklink git message
end
