" see :h defaults.vim for more details
unlet! skip_default_vim
source $VIMRUNTIME/defaults.vim

" settings {{{
set laststatus=2

set number
set relativenumber

set ignorecase
set smartcase
set infercase

set splitright
set splitbelow

set noswapfile

set clipboard+=unnamed

set breakindent
set linebreak
set nojoinspaces
set autoindent

set autowrite
set autoread

" XXX see :h fo-table for more details
" I prefer to wrap the text automatically, but not comments
set formatoptions=t
set formatoptions+=r
set formatoptions+=o
set formatoptions+=/
set formatoptions+=q
set formatoptions+=n
set formatoptions+=l
set formatoptions+=1
set formatoptions+=j
" set textwidth=70

" XXX see :help sortmess for more info
set shortmess=a " short for shortmess=filmnrwx
set shortmess+=o
set shortmess+=O
set shortmess+=s
set shortmess+=t
set shortmess+=T
set shortmess+=W
set shortmess+=I

set wildmenu
set wildoptions=pum
set wildmode=longest:full
set wildmode+=full

set list
set listchars=nbsp:⦸
set listchars+=extends:»
set listchars+=precedes:«
set listchars+=tab:▷⋯
set listchars+=trail:•

set spelllang=en,nl
" end settings }}}

" autocommands {{{
" Indicate insert mode using cursorline
function! AruInsertModeAutocmds() abort
  augroup AruInsertMode
    autocmd!
    autocmd InsertEnter,InsertLeave * set cursorline!
  augroup END
endfunction
call AruInsertModeAutocmds()

function! AruWindowAutocmds() abort
  augroup AruWindow
    autocmd!
    autocmd VimResized * wincmd =
  augroup END
endfunction
call AruWindowAutocmds()

function! AruHelptagsAutocmds() abort
  augroup AruHelptags
    autocmd!
    autocmd VimEnter * helptags ALL
  augroup END
endfunction
call AruHelptagsAutocmds()

" end autocommands }}}

" keybindings {{{
let mapleader = "\<Space>"
nmap <leader>so :source $MYVIMRC<cr>
nmap j gj
nmap k gk

function! AruFiletypeKeybindings() abort
  augroup AruFiletypeKeys
    autocmd!
    autocmd FileType help nmap <buffer> q :close<cr>
    autocmd FileType qf nmap <buffer> q :close<cr>
    autocmd FileType fugitive nmap <buffer> q gq
  augroup END
endfunction
call AruFiletypeKeybindings()

" end keybindings }}}

" statusline {{{1
set statusline=\ 
set statusline+=%<
set statusline+=%{aru#statusline_fileprefix()}
set statusline+=%t
set statusline+=\ 
set statusline+=%([%{aru#statusline_ft()}%{aru#statusline_fenc()}%R%M]%)
set statusline+=%=
set statusline+=\ 
set statusline+=%l:%L:%P
set statusline+=\ 
" }}}

" spacing {{{1
" XXX Uncomment the following settings to indent using (two) spaces if vim does
" not ship with editorconfig plugin
" set expandtab
" set tabstop=2
" set shiftwidth=2
" set smarttab
packadd editorconfig
" }}}

" pack {{{1
" vim-plug {{{2
" XXX Use single quotes as per vim-plug README
call plug#begin()
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-apathy'
Plug 'tpope/vim-git'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-commentary'
Plug 'wincent/terminus'
Plug 'wincent/loupe'
Plug 'wincent/ferret'
Plug 'wincent/pinnacle'
Plug 'junegunn/vim-easy-align'
if isdirectory('/usr/local/opt/fzf')
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
endif
Plug 'lervag/vimtex'
Plug 'https://git.sr.ht/~leon_plickat/paige'
call plug#end()
" end vim-plug}}}
" vimtex {{{2
let g:vimtex_fold_enabled = 1 " turn on folding in tex files
let g:vimtex_bib_fold_enabled = 1 " turn on folding in bib files
" end vimtex}}}
" fzf {{{2
nmap <leader>t :Files<cr>
nmap <leader><leader> :Buffers<cr>
nmap <leader>h :Helptags<cr>
nmap <leader>l :BLines<cr>

" XXX stolen from fzf.vim README
" Preview window is hidden by default. You can toggle it with ctrl-/.
" It will show on the right with 50% width, but if the width is smaller
" than 70 columns, it will show above the candidate list
let g:fzf_vim = {}
let g:fzf_vim.preview_window = []
" end fzf}}}
" markdown {{{2
let g:markdown_folding = 1
" end markdown}}}
" ferret {{{2
let g:FerretMap = 0 " do not create keybindings
" end ferret }}}
" end pack }}}

" highlights {{{1
set termguicolors
color retrobox

function! AruAutoBackground() abort
  augroup AruAutoBackground
    autocmd!
    autocmd FocusGained,VimEnter * call aru#set_background()
  augroup END
endfunction
call AruAutoBackground()
" end highlights }}}

" vim:foldmethod=marker foldlevelstart=99
