if &loadplugins
  if has('packages')
    packadd! vim-rsi
    packadd! vim-sleuth
    packadd! vim-scriptease
    packadd! vim-fugitive
    packadd! vim-commentary
    packadd! vim-dispatch
    packadd! vim-projectionist
    packadd! vim-eunuch
    packadd! vim-surround
    packadd! vim-rhubarb
    packadd! vim-repeat
    packadd! vim-clipper
    packadd! loupe
    packadd! terminus
    packadd! pinnacle
    packadd! command-t
    packadd! ferret
    packadd! vim-easydir
    packadd! indentline
    packadd! vim-slime
    packadd! vim-test
    packadd! vim-lion
    packadd! vim-tmux-navigator
    packadd! ultisnips
    packadd! vim-json
    packadd! vimtex
    packadd! vim-textobj-comment
    packadd! vim-textobj-user
    packadd! base16-vim
    packadd! vim-pandoc
    packadd! vim-pandoc-syntax
    if has('nvim')
      packadd! float-preview
      packadd! languageclient-neovim
    endif
  else
    source $HOME/.vim/pack/bundle/opt/vim-pathogen/autoload/pathogen.vim
    call pathogen#infect('pack/bundle/opt/{}')
  endif
endif

" Must come *after* the `:packadd!` calls above otherwise the contents of
" package "ftdetect" directories won't be evaluated.
filetype indent plugin on
syntax on

let mapleader = "\<Space>"
let maplocalleader="\\"
