call plug#begin('~/.vim/bundle')

Plug 'Raimondi/delimitMate'
Plug 'christoomey/vim-tmux-navigator'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-dispatch'
Plug 'radenling/vim-dispatch-neovim'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim', { 'for': ['pandoc', 'markdown'] }
Plug 'junegunn/limelight.vim', { 'for': ['pandoc', 'markdown'] }
Plug 'wincent/loupe'
Plug 'wincent/terminus'
Plug 'chriskempson/base16-vim'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'editorconfig/editorconfig-vim'
Plug 'vim-pandoc/vim-pandoc', { 'for': ['pandoc', 'markdown'] }
Plug 'vim-pandoc/vim-pandoc-syntax', { 'for': ['pandoc', 'markdown'] }
Plug 'mhinz/vim-grepper'
Plug 'dag/vim-fish', { 'for': 'fish' }

call plug#end()

let mapleader = " "
