#!/usr/bin/env fish

function install
    brew install pyenv
end

function link
    _mklink pyenv pyenv.fish "$FISH_CONFIG_HOME"
end

function unlink
    _cleanup pyenv "$FISH_CONFIG_HOME/pyenv.fish"
end
