#!/usr/bin/env fish

function install
    brew tap d12frosted/emacs-plus
    brew install emacs-plus --without-spacemacs-icon

    git clone git@github.com:arumoy-shome/emacs.d.git "$HOME/.emacs.d"

    # install ghostscript, required for DocView
    brew install ghostscript
end
