#!/usr/bin/env fish
source env

function install
    brew install fish

    set fish (which fish)
    test "$SHELL" = $fish; or chsh -s $fish (whoami)
    grep -q $fish /etc/shells; or echo $fish | sudo tee -a /etc/shells > /dev/null
end

function link
    _mklink fish config.fish
    _mklink fish functions
end
